# Generated by Django 4.2.6 on 2023-11-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='stud',
        ),
    ]
